listen_addr: :8080
auth_token: "change-me"
internal_cidrs: ["127.0.0.0/8","192.168.0.0/16","10.0.0.0/8","172.16.0.0/12","fd00::/8"]
allow_out_ports: [80,443,853,22,123]
doh_hosts: ["cloudflare-dns.com","dns.google","dns.quad9.net","doh.opendns.com","dns.adguard.com"]
